# change the followings to match your Github username and repo name
baseurl: "/tailpages" # the name of your github repo
url: "https://zeerg.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "A Little Hosted Page About Me"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Tom Bowyer
author-bio: Security/Gaming/Family/Mindfullness  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Resume
  permalink: resume
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: false
instagram: false
github: https://github.com/zeerg
linkedin: https://www.linkedin.com/in/tom-b-610208206/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/zeerg/tailpages

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
